### ISSUE TITLE
Flow warnings

### ISSUE THREAD

**Issue by steida** [gaearon/react-side-effect#25]
I don't know why, by from zilions Node modules I have in Este, only this library produces Flow warnings. Probably something with `fbjs`.

![screen shot 2016-08-10 at 03 58 26](https://cloud.githubusercontent.com/assets/66249/17539472/d8d42470-5eae-11e6-8f67-083e98813af8.png)

**Comment by glenjamin** [comment]
This module seems to be using a very old version of `fbjs`, it's not using much of its functionality and given the warning on https://github.com/facebook/fbjs I think it might be better to inline the relevant code or replace those uses with another module rather than updating to the latest fbjs.

@gaearon Would you take a PR for that? I'm open to adopting this if your focus is elsewhere these days - it looks like it'll be fairly light touch :)

**Comment by gaearon** [comment]
Yea totally this shouldn't depend on fbjs. Happy to take a PR.

**Comment by glenjamin** [comment]
You're supposed to be on holiday! 🏖

**Comment by gaearon** [comment]
I'll merge it when I'm bored 👯

**Comment by lourd** [comment]
v1.1.0 no longer depends on fbjs. I'm closing this for now. Please let me know this if this is still an issue
